"""initial schema

Revision ID: 997b26573843
Revises:
Create Date: 2026-04-06 22:24:40.735856

"""

from datetime import datetime, timezone
from typing import Sequence, Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997b26573843"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _default_system_config_rows() -> list[dict[str, object]]:
    timestamp = datetime.now(timezone.utc)
    return [
        {
            "id": str(uuid4()),
            "config_key": "crawl.default_limits",
            "config_name": "Default crawl limits",
            "config_group": "crawl",
            "config_value": {
                "requested_video_limit": 100,
                "max_pages": 5,
                "min_sleep_seconds": 1.5,
                "max_sleep_seconds": 5.0,
            },
            "description": "Default limits for keyword-based crawl tasks.",
            "is_active": True,
            "created_at": timestamp,
            "updated_at": timestamp,
        },
        {
            "id": str(uuid4()),
            "config_key": "crawl.ip_strategy",
            "config_name": "Default IP strategy",
            "config_group": "crawl",
            "config_value": {
                "mode": "local_sleep",
                "enable_proxy": False,
                "proxy_provider": None,
            },
            "description": "Use local IP with sleep throttling as the default strategy.",
            "is_active": True,
            "created_at": timestamp,
            "updated_at": timestamp,
        },
        {
            "id": str(uuid4()),
            "config_key": "analysis.scoring_weights",
            "config_name": "Composite score weights",
            "config_group": "analysis",
            "config_value": {
                "relevance_weight": 0.6,
                "heat_weight": 0.4,
                "heat_dimensions": [
                    "view_count",
                    "like_count",
                    "coin_count",
                    "favorite_count",
                    "reply_count",
                    "danmaku_count",
                ],
            },
            "description": "Default weights for relevance and popularity scoring.",
            "is_active": True,
            "created_at": timestamp,
            "updated_at": timestamp,
        },
        {
            "id": str(uuid4()),
            "config_key": "analysis.topic_clustering",
            "config_name": "Topic clustering defaults",
            "config_group": "analysis",
            "config_value": {
                "max_topic_keywords": 5,
                "min_cluster_size": 2,
                "fallback_primary_topic": "unclassified",
            },
            "description": "Default settings for topic grouping and normalization.",
            "is_active": True,
            "created_at": timestamp,
            "updated_at": timestamp,
        },
        {
            "id": str(uuid4()),
            "config_key": "ai.summary_defaults",
            "config_name": "AI summary defaults",
            "config_group": "ai",
            "config_value": {
                "model": "gpt-4o-mini",
                "summary_max_length": 200,
                "topic_count": 5,
                "prompt_version": "v1",
            },
            "description": "Default settings for per-video AI summaries and topic extraction.",
            "is_active": True,
            "created_at": timestamp,
            "updated_at": timestamp,
        },
    ]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_task",
        sa.Column("keyword", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "queued",
                "running",
                "partial_success",
                "success",
                "failed",
                "cancelled",
                name="taskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("requested_video_limit", sa.Integer(), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column(
            "min_sleep_seconds", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "max_sleep_seconds", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("enable_proxy", sa.Boolean(), nullable=False),
        sa.Column("source_ip_strategy", sa.String(length=50), nullable=False),
        sa.Column("total_candidates", sa.Integer(), nullable=False),
        sa.Column("processed_videos", sa.Integer(), nullable=False),
        sa.Column("analyzed_videos", sa.Integer(), nullable=False),
        sa.Column("clustered_topics", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extra_params", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_task")),
    )
    op.create_index(
        op.f("ix_crawl_task_crawl_task_keyword"),
        "crawl_task",
        ["keyword"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_task_crawl_task_status"), "crawl_task", ["status"], unique=False
    )
    op.create_table(
        "system_config",
        sa.Column("config_key", sa.String(length=128), nullable=False),
        sa.Column("config_name", sa.String(length=255), nullable=False),
        sa.Column("config_group", sa.String(length=64), nullable=False),
        sa.Column("config_value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_config")),
        sa.UniqueConstraint("config_key", name=op.f("uq_system_config_config_key")),
    )
    op.create_index(
        op.f("ix_system_config_system_config_config_group"),
        "system_config",
        ["config_group"],
        unique=False,
    )
    system_config_table = sa.table(
        "system_config",
        sa.column("id", sa.String(length=36)),
        sa.column("config_key", sa.String(length=128)),
        sa.column("config_name", sa.String(length=255)),
        sa.column("config_group", sa.String(length=64)),
        sa.column("config_value", sa.JSON()),
        sa.column("description", sa.Text()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(system_config_table, _default_system_config_rows())
    op.create_table(
        "video",
        sa.Column("bvid", sa.String(length=32), nullable=False),
        sa.Column("aid", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_mid", sa.String(length=64), nullable=True),
        sa.Column("cover_url", sa.String(length=1024), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video")),
        sa.UniqueConstraint("aid", name=op.f("uq_video_aid")),
    )
    op.create_index(op.f("ix_video_video_bvid"), "video", ["bvid"], unique=True)
    op.create_table(
        "crawl_task_log",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "debug", "info", "warning", "error", name="loglevel", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "task",
                "search",
                "detail",
                "subtitle",
                "text",
                "ai",
                "topic",
                "export",
                name="taskstage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_crawl_task_log_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_task_log")),
    )
    op.create_index(
        op.f("ix_crawl_task_log_crawl_task_log_task_id"),
        "crawl_task_log",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "task_video",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("search_rank", sa.Integer(), nullable=True),
        sa.Column("keyword_hit_title", sa.Boolean(), nullable=False),
        sa.Column("keyword_hit_description", sa.Boolean(), nullable=False),
        sa.Column("keyword_hit_tags", sa.Boolean(), nullable=False),
        sa.Column("relevance_score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("heat_score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("composite_score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_task_video_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_task_video_video_id_video"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_video")),
        sa.UniqueConstraint("task_id", "video_id", name=op.f("uq_task_video_task_id")),
    )
    op.create_index(
        op.f("ix_task_video_task_video_task_id"),
        "task_video",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_video_task_video_video_id"),
        "task_video",
        ["video_id"],
        unique=False,
    )
    op.create_table(
        "topic_cluster",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("video_count", sa.Integer(), nullable=False),
        sa.Column(
            "total_heat_score", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "average_heat_score", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("cluster_order", sa.Integer(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_topic_cluster_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_cluster")),
        sa.UniqueConstraint(
            "task_id", "normalized_name", name=op.f("uq_topic_cluster_task_id")
        ),
    )
    op.create_index(
        op.f("ix_topic_cluster_topic_cluster_task_id"),
        "topic_cluster",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "video_metric_snapshot",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("view_count", sa.BigInteger(), nullable=False),
        sa.Column("like_count", sa.BigInteger(), nullable=False),
        sa.Column("coin_count", sa.BigInteger(), nullable=False),
        sa.Column("favorite_count", sa.BigInteger(), nullable=False),
        sa.Column("share_count", sa.BigInteger(), nullable=False),
        sa.Column("reply_count", sa.BigInteger(), nullable=False),
        sa.Column("danmaku_count", sa.BigInteger(), nullable=False),
        sa.Column("metrics_payload", sa.JSON(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_video_metric_snapshot_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_video_metric_snapshot_video_id_video"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_metric_snapshot")),
    )
    op.create_index(
        op.f("ix_video_metric_snapshot_video_metric_snapshot_task_id"),
        "video_metric_snapshot",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_metric_snapshot_video_metric_snapshot_video_id"),
        "video_metric_snapshot",
        ["video_id"],
        unique=False,
    )
    op.create_table(
        "video_text_content",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("has_description", sa.Boolean(), nullable=False),
        sa.Column("has_subtitle", sa.Boolean(), nullable=False),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("subtitle_text", sa.Text(), nullable=True),
        sa.Column("combined_text", sa.Text(), nullable=False),
        sa.Column("combined_text_hash", sa.String(length=64), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_video_text_content_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_video_text_content_video_id_video"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_text_content")),
        sa.UniqueConstraint(
            "task_id", "video_id", name=op.f("uq_video_text_content_task_id")
        ),
    )
    op.create_index(
        op.f("ix_video_text_content_video_text_content_task_id"),
        "video_text_content",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_video_text_content_video_text_content_video_id"),
        "video_text_content",
        ["video_id"],
        unique=False,
    )
    op.create_table(
        "ai_summary",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("text_content_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("topics", sa.JSON(), nullable=False),
        sa.Column("primary_topic", sa.String(length=255), nullable=True),
        sa.Column("tone", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("raw_response", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_ai_summary_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["text_content_id"],
            ["video_text_content.id"],
            name=op.f("fk_ai_summary_text_content_id_video_text_content"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_ai_summary_video_id_video"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_summary")),
        sa.UniqueConstraint("task_id", "video_id", name=op.f("uq_ai_summary_task_id")),
    )
    op.create_index(
        op.f("ix_ai_summary_ai_summary_task_id"),
        "ai_summary",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_summary_ai_summary_text_content_id"),
        "ai_summary",
        ["text_content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_summary_ai_summary_video_id"),
        "ai_summary",
        ["video_id"],
        unique=False,
    )
    op.create_table(
        "video_subtitle_segment",
        sa.Column("text_content_id", sa.String(length=36), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("start_seconds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("end_seconds", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["text_content_id"],
            ["video_text_content.id"],
            name=op.f("fk_video_subtitle_segment_text_content_id_video_text_content"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_subtitle_segment")),
        sa.UniqueConstraint(
            "text_content_id",
            "segment_index",
            name=op.f("uq_video_subtitle_segment_text_content_id"),
        ),
    )
    op.create_index(
        op.f("ix_video_subtitle_segment_video_subtitle_segment_text_content_id"),
        "video_subtitle_segment",
        ["text_content_id"],
        unique=False,
    )
    op.create_table(
        "topic_video_relation",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("topic_cluster_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("ai_summary_id", sa.String(length=36), nullable=True),
        sa.Column("relevance_score", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_summary_id"],
            ["ai_summary.id"],
            name=op.f("fk_topic_video_relation_ai_summary_id_ai_summary"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["crawl_task.id"],
            name=op.f("fk_topic_video_relation_task_id_crawl_task"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_cluster_id"],
            ["topic_cluster.id"],
            name=op.f("fk_topic_video_relation_topic_cluster_id_topic_cluster"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["video.id"],
            name=op.f("fk_topic_video_relation_video_id_video"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_video_relation")),
        sa.UniqueConstraint(
            "task_id",
            "topic_cluster_id",
            "video_id",
            name=op.f("uq_topic_video_relation_task_id"),
        ),
    )
    op.create_index(
        op.f("ix_topic_video_relation_topic_video_relation_ai_summary_id"),
        "topic_video_relation",
        ["ai_summary_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_video_relation_topic_video_relation_task_id"),
        "topic_video_relation",
        ["task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_video_relation_topic_video_relation_topic_cluster_id"),
        "topic_video_relation",
        ["topic_cluster_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_video_relation_topic_video_relation_video_id"),
        "topic_video_relation",
        ["video_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_topic_video_relation_topic_video_relation_video_id"),
        table_name="topic_video_relation",
    )
    op.drop_index(
        op.f("ix_topic_video_relation_topic_video_relation_topic_cluster_id"),
        table_name="topic_video_relation",
    )
    op.drop_index(
        op.f("ix_topic_video_relation_topic_video_relation_task_id"),
        table_name="topic_video_relation",
    )
    op.drop_index(
        op.f("ix_topic_video_relation_topic_video_relation_ai_summary_id"),
        table_name="topic_video_relation",
    )
    op.drop_table("topic_video_relation")
    op.drop_index(
        op.f("ix_video_subtitle_segment_video_subtitle_segment_text_content_id"),
        table_name="video_subtitle_segment",
    )
    op.drop_table("video_subtitle_segment")
    op.drop_index(op.f("ix_ai_summary_ai_summary_video_id"), table_name="ai_summary")
    op.drop_index(
        op.f("ix_ai_summary_ai_summary_text_content_id"), table_name="ai_summary"
    )
    op.drop_index(op.f("ix_ai_summary_ai_summary_task_id"), table_name="ai_summary")
    op.drop_table("ai_summary")
    op.drop_index(
        op.f("ix_video_text_content_video_text_content_video_id"),
        table_name="video_text_content",
    )
    op.drop_index(
        op.f("ix_video_text_content_video_text_content_task_id"),
        table_name="video_text_content",
    )
    op.drop_table("video_text_content")
    op.drop_index(
        op.f("ix_video_metric_snapshot_video_metric_snapshot_video_id"),
        table_name="video_metric_snapshot",
    )
    op.drop_index(
        op.f("ix_video_metric_snapshot_video_metric_snapshot_task_id"),
        table_name="video_metric_snapshot",
    )
    op.drop_table("video_metric_snapshot")
    op.drop_index(
        op.f("ix_topic_cluster_topic_cluster_task_id"), table_name="topic_cluster"
    )
    op.drop_table("topic_cluster")
    op.drop_index(op.f("ix_task_video_task_video_video_id"), table_name="task_video")
    op.drop_index(op.f("ix_task_video_task_video_task_id"), table_name="task_video")
    op.drop_table("task_video")
    op.drop_index(
        op.f("ix_crawl_task_log_crawl_task_log_task_id"), table_name="crawl_task_log"
    )
    op.drop_table("crawl_task_log")
    op.drop_index(op.f("ix_video_video_bvid"), table_name="video")
    op.drop_table("video")
    op.drop_index(
        op.f("ix_system_config_system_config_config_group"), table_name="system_config"
    )
    op.drop_table("system_config")
    op.drop_index(op.f("ix_crawl_task_crawl_task_status"), table_name="crawl_task")
    op.drop_index(op.f("ix_crawl_task_crawl_task_keyword"), table_name="crawl_task")
    op.drop_table("crawl_task")
    # ### end Alembic commands ###
